# -*- coding: utf-8 -*-
r"""Generates the documented file tree, and checks it against the repository.

The layout is shown twice -- in ``README.md`` and in
``docs/source/installation.rst`` -- because the two are read in different
places.  Both are **generated** from `TREE` below rather than maintained by
hand, so there is one place to edit and no way for the two copies to disagree.

They had disagreed, which is why this exists: twenty-one tracked files were
missing from the README's tree, and not only recent ones -- ``plotting.rst``,
``avgprob.py`` and five test modules had been absent for some time.  A tree
maintained by hand drifts silently, because nothing reads it except a person
who already knows the layout.

`TREE` is the ordered list of paths, each with the one-line comment that
appears beside it.  The order is a curated reading order, not alphabetical, and
the comments are prose: neither can be derived from the filesystem, which is why
the table exists at all.  What *is* derived is membership --
`test_tree_matches_git` requires the file entries to be exactly ``git
ls-files``, minus the collapsed directories below, so adding or removing a
tracked file fails the suite until the table is updated.

To update both documents after changing `TREE`, or after adding a file::

    python tests/test_file_tree.py --write

Running it with no arguments reports whether they are current without touching
anything.
"""

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
README = os.path.join(ROOT, 'README.md')
INSTALL_RST = os.path.join(ROOT, 'docs', 'source', 'installation.rst')

ROOT_LABEL = 'Magnus/'

# Column at which a trailing comment starts.
COMMENT_COLUMN = 36

# Directories shown as a single entry rather than enumerated, and exempt from
# the membership check.  Each holds many files of one kind, none of which a
# reader needs named: developer findings and adversarial batteries, figures
# lifted out of the executed notebooks, and notebook output.  Listing them
# would triple the tree without telling anyone anything.
COLLAPSED = ('docs/dev/', 'img/gallery/', 'fig/', 'resources/paper/figs/')

TREE = [
    ('.github/', 'GitHub Actions workflows: tests, lint, notebooks, docs, publishing'),
    ('.github/workflows/', None),
    ('.github/workflows/lint.yml', 'Ruff lint (blocking) + CLI-reference drift check'),
    ('.github/workflows/notebooks.yml', 'Executes every notebook; paths-filtered, so docs-only changes skip it'),
    ('.github/workflows/pages.yml', 'GitHub Pages deployment for the Sphinx documentation'),
    ('.github/workflows/publish.yml', 'PyPI (OIDC) automated publishing workflow, on GitHub Release'),
    ('.github/workflows/tests.yml', 'GitHub Actions CI testing pipeline (Python 3.10-3.13) + coverage'),
    ('.gitignore',
     'Build, cache and generated-output artifacts'),
    ('CHANGELOG.md', 'Version history (Keep a Changelog format)'),
    ('CITATION.cff', 'Machine-readable citation metadata; drives GitHub\'s "Cite this repository"'),
    ('LICENSE', 'GNU GPL v3 (GPL-3.0-only), the full license text'),
    ('README.md', 'This file'),
    ('docs/', 'Sphinx documentation configuration and source'),
    ('docs/Makefile', 'Build commands for Unix'),
    ('docs/check_doc_snippets.py',
     'Checks the code snippets quoted in the prose pages still run'),
    ('docs/dev/', None),
    ('docs/make.bat', 'Build commands for Windows'),
    ('docs/make_figures.py', 'Regenerates the data-driven SVG in source/_static/'),
    ('docs/regen_cli_help.py', 'Regenerates the --help block quoted in source/cli.rst'),
    ('docs/requirements.txt', 'Sphinx + theme + extensions needed to build the docs'),
    ('docs/source/', None),
    ('docs/source/_static/', None),
    ('docs/source/_static/adiabatic_avoided_crossing.svg',
     'Hand-authored: adiabatic against diabatic at a crossing'),
    ('docs/source/_static/api_layers.svg',
     'Generated by docs/make_figures.py: the three layers of oscprob'),
    ('docs/source/_static/adiabatic_segmentation.svg',
     'Hand-authored: adiabatic / patch / adiabatic along the ray'),
    ('docs/source/_static/adiabatic_speedup.svg',
     'Generated by docs/make_figures.py from the measured grid'),
    ('docs/source/_static/averaging_regimes.svg',
     'Hand-authored: when averaging removes an error and when it does not'),
    ('docs/source/_static/call_sequence.svg',
     'Generated by docs/make_figures.py: what is built, in what order, per call'),
    ('docs/source/_static/magnus_logo.png',
     'Sidebar logo'),
    ('docs/source/_static/module_layout.svg',
     'Generated by docs/make_figures.py: the real internal import graph'),
    ('docs/source/adiabatic_strategy.rst', 'The adiabatic + Magnus hybrid strategy: derivation, diagrams, validation'),
    ('docs/source/api_reference.rst', 'Wraps the autoapi-generated module pages'),
    ('docs/source/architecture.rst', 'The wrapper/middle/primordial layering, with diagrams'),
    ('docs/source/averaged_probability.rst',
     'Phase-averaged probabilities: derivation, diagram, validation'),
    ('docs/source/changelog.rst', 'Renders the root CHANGELOG.md via myst-parser'),
    ('docs/source/citing.rst', 'How to cite the software, and what to state in the text'),
    ('docs/source/cli.rst', 'Command-line calculator: flag reference and examples'),
    ('docs/source/comparison.rst',
     'Against NuOscProbExact and nuSQuIDS: where each method wins, from notebook 25'),
    ('docs/source/conf.py', 'Sphinx build configuration (autoapi + napoleon + bibtex + mermaid + myst)'),
    ('docs/source/diagnostics.rst',
     'What rtol really controls, what each safeguard cannot do, every warning'),
    ('docs/source/engines.rst',
     'Which engine answers a call, and how the dispatch order is decided'),
    ('docs/source/expansion_terms.rst', 'The Omega_k terms to any order, and how they are generated'),
    ('docs/source/functions.rst', 'Full osc_prob_{2,3,4,5}nu_* listing, grouped by environment/scenario'),
    ('docs/source/index.rst', 'Master documentation page: overview, features, when Magnus wins'),
    ('docs/source/installation.rst', 'Requirements, install instructions, file tree'),
    ('docs/source/methodology.rst', 'The Magnus expansion, integrators, and performance engineering'),
    ('docs/source/performance.rst',
     'Where the time goes, and the population every tuned constant was measured on'),
    ('docs/source/plotting.rst', 'The pre-packaged plotting tools'),
    ('docs/source/quickstart.rst', 'Worked Python-API code examples for every entry point'),
    ('docs/source/recipes.rst', 'What Magnus can compute, with the code -- executed at build time'),
    ('docs/source/references.rst', 'Bibliography page rendering'),
    ('docs/source/refs.bib', 'BibTeX citations for the Magnus-expansion and PREM literature'),
    ('docs/source/tutorials.rst', 'Guide to the numbered example notebooks in notebooks/'),
    ('fig/', 'Plots produced by the example notebooks'),
    ('img/', 'Figures used by the documentation'),
    # The shrunk animation clips from notebook 27.  Their raw originals live in
    # img/raw/ and are gitignored; these are what a reader sees without paying
    # the hour the render costs.
    ('img/anim_cp.gif', 'Animated: the CP phase running through 2 pi'),
    ('img/anim_earth.gif', 'Animated: a chord swinging to a detector at the South Pole'),
    ('img/anim_shock.gif', 'Animated: a supernova shock front sweeping outward'),
    ('img/anim_slabs.gif', 'Animated: a profile cut into more and more slabs'),
    ('img/anim_solar_nsi.gif', 'Animated: the Sun, with a non-standard interaction dialed up'),
    ('img/anim_sterile.gif', 'Animated: a sterile state as its mass splitting grows'),
    ('img/anim_wave.gif', 'Animated: a density crest traveling along the baseline'),
    ('img/gallery/', 'Figures lifted from the executed notebooks, embedded in the docs'),
    ('notebooks/', 'Numbered Jupyter notebooks -- see docs/source/tutorials.rst'),
    ('notebooks/01_magnus_introduction.ipynb',
     'The shortest path to a probability'),
    ('notebooks/02_magnus_2nu_vacuum_matter.ipynb',
     'Two flavors, across seven matter profiles'),
    ('notebooks/03_magnus_3nu_vacuum_matter.ipynb',
     'The same, with three flavors and a CP phase'),
    ('notebooks/04_magnus_long_baseline.ipynb',
     'Between two points on the surface'),
    ('notebooks/05_magnus_biprobability.ipynb',
     'The CP ellipse'),
    ('notebooks/06_magnus_oscillograms.ipynb',
     'Zenith angle against energy, in one call'),
    ('notebooks/07_magnus_bsm_sterile_nu.ipynb',
     'Four and five flavors'),
    ('notebooks/08_magnus_bsm_nsi.ipynb',
     'Non-standard interactions'),
    ('notebooks/09_magnus_bsm_liv.ipynb',
     'Lorentz-invariance violation'),
    ('notebooks/10_magnus_averaged_probability.ipynb',
     'What survives when the phase is unresolvable'),
    ('notebooks/11_magnus_matrix_exponential.ipynb',
     'How exp(Omega) is actually built'),
    ('notebooks/12_magnus_adiabatic_hybrid_strategy.ipynb',
     "'auto' against 'magnus', timed against solve_ivp"),
    ('notebooks/13_magnus_tabulated_solar_model.ipynb',
     'A real BS05 profile: an error that is a phase'),
    ('notebooks/14_magnus_supernova_shock.ipynb',
     'A shock front: an error that is an envelope'),
    ('notebooks/15_magnus_antineutrinos.ipynb',
     'Conjugate and flip, and two ways to get it half right'),
    ('notebooks/16_magnus_exact_vs_approximations.ipynb',
     'Where the textbook formulas are exact, and where the substitution breaks'),
    ('notebooks/17_magnus_ordering_and_octant.ipynb',
     'The sign of D31, and how large the two open questions are'),
    ('notebooks/18_magnus_unusual_density_profiles.ipynb',
     'Arrangement beats the mean, except for one exact symmetry'),
    ('notebooks/19_magnus_custom_hamiltonian.ipynb',
     'The H_func contract, and the vectorization trick'),
    ('notebooks/20_magnus_numerical_edge_cases.ipynb',
     'Degeneracies that return numbers, and the nine warnings'),
    ('notebooks/21_magnus_what_tolerance_means.ipynb',
     'rtol is a stopping criterion, not an error bound'),
    ('notebooks/22_magnus_which_engine_answered.ipynb',
     'strategy_info, and an error bar with no oracle'),
    ('notebooks/23_magnus_when_averaging_helps.ipynb',
     'Phase error falls away, envelope error does not'),
    ('notebooks/24_magnus_performance.ipynb',
     'What is worth doing, and when each trick is worth nothing'),
    ('notebooks/25_magnus_against_other_codes.ipynb',
     'Where a closed form wins, and a conventions trap that looks like accuracy'),
    ('notebooks/26_magnus_nufit_evolution.ipynb',
     'How the NuFIT likelihood, not just the best fit, moves the probability'),
    ('notebooks/27_magnus_animations.ipynb',
     'Ten sweeps as filmstrips; RENDER = True writes them as GIFs'),
    ('notebooks/28_magnus_paper_figures.ipynb',
     "Every figure in the CPC article, in one run"),
    ('notebooks/29_magnus_pseudo_dirac.ipynb',
     'Tiny splittings, coherent blocks, and where the effect is invisible'),
    ('notebooks/README.md', 'This file'),
    ('notebooks/make_notebooks.py', 'BUILDS the notebooks above -- edit this, not the .ipynb'),
    ('notebooks/external_speed_accuracy.json',
     "Five external codes' speed and accuracy (NuOscProbExact project)"),
    ('notebooks/external_prem_speed_accuracy.json',
     "Notebook 25 section 5: the same, on a PREM chord, both codes batched"),
    ('notebooks/external_profile_benchmarks.json',
     "Notebook 25 section 9: smooth-profile speed/accuracy, all codes on one machine"),
    ('notebooks/external_shock_benchmarks.json',
     "Notebook 25 section 11: the supernova shock, both front widths"),
    ('notebooks/external_shock_4nu.json',
     "Notebook 25 section 12: the same shock at 3+1"),
    ('notebooks/external_shock_nsi.json',
     "Notebook 25 section 13: the same shock with NSI"),
    ('notebooks/external_solar_nusquids.json',
     "Notebook 25 section 10: nuSQuIDS's energy-averaged solar survival probability"),
    ('notebooks/gen_profile_benchmarks.py',
     'GENERATES external_profile_benchmarks.json -- needs the external codes'),
    ('notebooks/gen_shock_benchmarks.py',
     'GENERATES external_shock_benchmarks.json -- runs notebook 14s own cells'),
    ('notebooks/gen_shock_4nu.py',
     'GENERATES external_shock_4nu.json -- the shock at 3+1, own DOP853 referee'),
    ('notebooks/gen_shock_nsi.py',
     'GENERATES external_shock_nsi.json -- the shock with NSI, own DOP853 referee'),
    ('notebooks/gen_solar_nusquids.py',
     'GENERATES external_solar_nusquids.json -- needs nuSQuIDS'),
    ('notebooks/make_nufit_chi2.py', "Extracts notebook 26's NuFIT chi^2 profiles"),
    ('notebooks/make_shock_reference.py', "Freezes notebook 14's solve_ivp oracle"),
    ('notebooks/matplotlibrc', 'Shared plot styling for the notebooks'),
    ('notebooks/paper_figure_cache.json',
     'Every paper-figure input that depends on the configuration and not on the run:'
     ' reference probabilities, order curves, and timings'),
    ('notebooks/nufit_chi2.json', 'Those profiles, v2.0-v6.1 (NuFIT collaboration)'),
    ('notebooks/shock_reference.json', 'That oracle, as exact hex floats'),
    ('pyproject.toml', 'Build system, dependencies, and the `magnus` console-script entry point'),
    ('resources/', 'Travels with the code; reaches neither the wheel nor the sdist'),
    ('resources/paper/', 'The Computer Physics Communications article documenting this package'),
    ('resources/paper/README.md', 'How to build the paper, and where each of its numbers comes from'),
    # Working notes for the paper, tracked so a session can pick the work up.
    ('resources/paper/HANDOVER-pseudodirac.md',
     'Brief for adding pseudo-Dirac neutrinos to the library'),
    ('resources/paper/API-pseudodirac.md',
     'The pseudo-Dirac API, summarized for the session writing the panel'),
    ('resources/paper/audit-criteria.md', 'What the manuscript audit checks'),
    ('resources/paper/review-crossread.md', 'A cross-read of the manuscript against the code'),
    ('resources/paper/main.tex', 'The paper -- ordinary LaTeX; a revision diff is mechanical'),
    ('resources/paper/refs.bib',
     "NuOscProbExact's bibliography, with the Magnus entries appended below a separator"),
    ('resources/paper/elsarticle.cls', 'Bundled, so the folder compiles without the Elsevier bundle'),
    ('resources/paper/elsarticle-num.bst', None),
    ('resources/paper/figs/', 'Its eight figures, written by notebook 28'),
    ('tools/', 'Standalone utilities that are not part of the package'),
    ('tools/make_demo_video.py',
     "Joins and shrinks notebook 27's clips; shared with NuOscProbExact"),
    ('src/', 'The package itself -- the only thing a `pip install` delivers'),
    ('src/magnus/', 'Main Python package'),
    ('src/magnus/__init__.py', 'Explicit named imports from the four hamiltonians{2,3,4,5}nu.py modules'),
    ('src/magnus/__main__.py', 'Entry point for `python -m magnus`'),
    ('src/magnus/adiabatic.py', "Adiabatic transport + Magnus-patch hybrid strategy (strategy='hybrid'/'auto')"),
    ('src/magnus/authors.py', 'Package author string (internal; not part of the public API)'),
    ('src/magnus/avgprob.py', 'Phase-averaged (decohered) probabilities'),
    ('src/magnus/cli.py', '`magnus` command-line calculator (also `python -m magnus`)'),
    ('src/magnus/earth.py', 'PREM density profile, chord/zenith-angle geometry'),
    ('src/magnus/expansionterms.py', 'Generates the Omega_k terms symbolically, to any order'),
    ('src/magnus/expmkernels.py',
     'Compiled Cayley-Hamilton matrix exponential for 2x2/3x3 (the numba backend)'),
    ('src/magnus/globaldefs.py', 'Units, physical constants, NuFit parameter sets'),
    ('src/magnus/hamiltonians/', '2nu-5nu Hamiltonians: vacuum, matter, NSI, LIV (the one true subpackage)'),
    ('src/magnus/hamiltonians/__init__.py', 'Explicit named imports from the four hamiltonians{2,3,4,5}nu.py modules'),
    ('src/magnus/hamiltonians/_angles.py', 'Interprets the four angles conventions; rejects an out-of-range sine'),
    ('src/magnus/hamiltonians/hamiltonians2nu.py', None),
    ('src/magnus/hamiltonians/hamiltonians3nu.py', None),
    ('src/magnus/hamiltonians/hamiltonians4nu.py', None),
    ('src/magnus/hamiltonians/hamiltonians5nu.py', None),
    ('src/magnus/hamiltonians/hamiltonians_pseudodirac.py',
     'Pseudo-Dirac spectra: per-mass-state pairing, and the sterile partners'),
    ('src/magnus/magnus.py', 'Magnus-expansion numerical core: term recursion, GL integrators, batched kernel'),
    ('src/magnus/matter.py', 'Density profiles, electron number density, CC potential'),
    ('src/magnus/oscprob.py', 'osc_prob and every physics-scenario wrapper (main API)'),
    ('src/magnus/oscprobstd.py', 'Closed-form 2nu/3nu probabilities (used to validate the wrapper API)'),
    ('src/magnus/plotting.py', 'Pre-packaged plotting tools: one call instead of thirty lines'),
    ('src/magnus/py.typed', 'PEP 561 marker: tells type checkers the annotations are real'),
    ('src/magnus/version.py', 'Resolves the version from pyproject.toml (internal)'),
    ('src/requirements.txt', 'Sphinx + theme + extensions needed to build the docs'),
    ('tests/', 'Test suite (pytest; runs in CI)'),
    ('tests/conftest.py', 'Path setup so magnus is importable without installation'),
    ('tests/test_adiabatic.py', 'Adiabatic + Magnus hybrid strategy: detection, merging, ODE cross-checks'),
    ('tests/test_angles.py', "The four `angles` conventions and the guards between them"),
    ('tests/test_avgprob.py', 'Phase-averaged probabilities'),
    ('tests/test_cli.py', 'magnus command-line calculator'),
    ('tests/test_pseudodirac.py',
     'Pseudo-Dirac Hamiltonians: the Dirac limit, blocks, and the factor of two'),
    ('tests/test_documented_examples.py',
     'Runs the code blocks in README.md and quickstart.rst'),
    ('tests/test_earth_matter.py', 'PREM profile, chord geometry, electron density'),
    ('tests/test_engines.py', 'Which engine answers, and the cross-checks between them'),
    ('tests/test_expansionterms.py', 'The symbolic term generator against the hand-written orders'),
    ('tests/test_expm_backend.py',
     'The two matrix-exponential backends, their switch, and degeneracies'),
    ('tests/test_fuzz_statistics.py', 'Randomized profiles, scored in bulk'),
    ('tests/test_file_tree.py',
     'This file: generates the tree above and checks it against git'),
    ('tests/test_globaldefs.py', 'NuFit historical parameter dict/loader'),
    ('tests/test_hamiltonians.py', 'Hamiltonian/mixing-matrix builders'),
    ('tests/test_invariants.py', 'Properties that must hold across the whole engine matrix'),
    ('tests/test_magnus_expansion.py', 'Magnus-core correctness (terms, orders, GL rates, unitarity)'),
    ('tests/test_oscprob.py', 'Oscillation-probability engine, closed-form and ODE cross-checks'),
    ('tests/test_palindrome.py', 'The palindromic-profile optimization and its gate'),
    ('tests/test_plotting.py', 'Pre-packaged plotting tools: house-style defaults, layouts'),
    ('tests/test_routine_listings.py',
     "Each module's Routine listings names every public function it defines"),
    ('tests/test_tolerance.py', 'What rtol/atol promise, and the effective-refinement gate'),
    ('tests/test_validation.py', 'Input-validation guards and their error messages'),
    ('tests/test_version.py', 'Version resolution from pyproject.toml / installed metadata'),
]


def render_tree(entries=None):
    r"""The tree as a list of lines, box-drawing connectors and all.

    Depth and connectors are derived from the paths alone, so `TREE` carries no
    drawing characters and reordering an entry cannot leave a stale one behind.

    ``entries`` defaults to the whole of `TREE`; pass a subset to render a
    partial tree, as `render_summary_tree` does.
    """
    entries = TREE if entries is None else entries
    paths = [p for p, _ in entries]
    depths = [p.rstrip('/').count('/') for p in paths]

    def has_later_sibling(index):
        """Another entry after `index`, at the same depth, under the same parent."""
        parts = paths[index].rstrip('/').split('/')
        for other, other_depth in zip(paths[index+1:], depths[index+1:]):
            other_parts = other.rstrip('/').split('/')
            if other_depth < depths[index]:
                return False          # left this subtree entirely
            if other_depth == depths[index] and other_parts[:-1] == parts[:-1]:
                return True
        return False

    # For each entry, whether each of its ancestors still has siblings to come:
    # that is what decides a vertical bar rather than blank space.
    trailing = []
    lines = [ROOT_LABEL]
    for index, (path, comment) in enumerate(entries):
        depth = depths[index]
        del trailing[depth:]
        prefix = ''.join('│   ' if more else '    ' for more in trailing[:depth])
        connector = '├── ' if has_later_sibling(index) else '└── '
        name = path.rstrip('/').split('/')[-1] + ('/' if path.endswith('/') else '')
        line = prefix + connector + name
        if comment:
            pad = max(COMMENT_COLUMN - len(line), 2)
            line = line + ' '*pad + '# ' + comment
        lines.append(line)
        trailing.append(has_later_sibling(index))
    return lines


def render_summary_tree():
    r"""The top level only, for the README.

    The README is also the PyPI long description (``readme = "README.md"`` in
    ``pyproject.toml``), and the full tree is 158 entries of which **27** are
    under ``src/`` -- so 83% of it describes files a ``pip install`` never
    delivers, rendered on a page whose readers have only the wheel.  The
    complete listing stays in ``docs/source/installation.rst``, where the reader
    has the repository in front of them.

    Generated from the same `TREE`, so the two cannot disagree and a new
    top-level directory cannot be forgotten here.
    """
    return render_tree([(p, c) for p, c in TREE if p.rstrip('/').count('/') == 0])


def _readme_block(text):
    lines = text.split('\n')
    start = next(i for i, l in enumerate(lines) if l.startswith('## File Tree'))
    # The opening fence carries an info string (```text); the closing one does
    # not.  Matching '```' exactly finds the CLOSING fence first and rewrites
    # the wrong region -- which is exactly what it did.
    opening = next(i for i, l in enumerate(lines[start:], start)
                   if l.startswith('```'))
    closing = next(i for i, l in enumerate(lines[opening+1:], opening+1)
                   if l.strip() == '```')
    return lines, opening + 1, closing


def _install_block(text):
    lines = text.split('\n')
    start = next(i for i, l in enumerate(lines) if l.startswith('File Tree'))
    fence = [i for i, l in enumerate(lines[start:], start)
             if l.strip() == '.. code-block:: text']
    begin = fence[0] + 2
    end = begin
    while end < len(lines) and (not lines[end].strip() or lines[end].startswith('   ')):
        end += 1
    while end > begin and not lines[end-1].strip():
        end -= 1
    return lines, begin, end


def current_readme_tree():
    with open(README) as handle:
        lines, start, end = _readme_block(handle.read())
    return lines[start:end]


def current_install_tree():
    with open(INSTALL_RST) as handle:
        lines, start, end = _install_block(handle.read())
    return [l[3:] if l.startswith('   ') else l for l in lines[start:end]]


def write():
    r"""Rewrites the block in both documents; returns those that changed."""
    generated = render_tree()
    changed = []

    summary = render_summary_tree()

    with open(README) as handle:
        text = handle.read()
    lines, start, end = _readme_block(text)
    if lines[start:end] != summary:
        lines[start:end] = summary
        with open(README, 'w') as handle:
            handle.write('\n'.join(lines))
        changed.append(README)

    with open(INSTALL_RST) as handle:
        text = handle.read()
    lines, start, end = _install_block(text)
    indented = ['   ' + l if l else l for l in generated]
    if lines[start:end] != indented:
        lines[start:end] = indented
        with open(INSTALL_RST, 'w') as handle:
            handle.write('\n'.join(lines))
        changed.append(INSTALL_RST)

    return changed


def test_tree_matches_git():
    r"""The file entries in `TREE` are exactly the tracked files.

    This is the check that stops the tree drifting: a file added to the
    repository fails here until it is given a line and a comment.
    """
    tracked = {p for p in subprocess.check_output(
        ['git', 'ls-files'], cwd=ROOT).decode().split()
        if not p.startswith(COLLAPSED)}
    listed = {p for p, _ in TREE if not p.endswith('/')}

    missing = sorted(tracked - listed)
    stale = sorted(listed - tracked)
    assert not missing, (
        'tracked but absent from TREE in tests/test_file_tree.py: %s'
        % ', '.join(missing))
    assert not stale, (
        'listed in TREE but not tracked: %s' % ', '.join(stale))


def test_collapsed_directories_are_listed_and_non_empty():
    r"""Each collapsed directory appears as an entry, and still has contents."""
    listed = {p for p, _ in TREE}
    tracked = subprocess.check_output(
        ['git', 'ls-files'], cwd=ROOT).decode().split()
    for prefix in COLLAPSED:
        assert prefix in listed, '%s is collapsed but not listed' % prefix
        assert any(p.startswith(prefix) for p in tracked), (
            '%s is collapsed but holds no tracked files' % prefix)


def test_every_directory_in_tree_has_a_parent_entry():
    r"""Each nested entry's parent is listed, and listed before it."""
    seen = set()
    for path, _ in TREE:
        trimmed = path.rstrip('/')
        if '/' in trimmed:
            parent = trimmed.rsplit('/', 1)[0] + '/'
            assert parent in seen, (
                '%s appears before its parent %s' % (path, parent))
        seen.add(path)


def test_readme_tree_is_generated():
    r"""README.md carries exactly what `render_summary_tree` produces."""
    assert current_readme_tree() == render_summary_tree(), (
        'the file tree in README.md is out of date; regenerate it with '
        '`python tests/test_file_tree.py --write`')


def test_readme_summary_covers_every_top_level_entry():
    r"""The abbreviated tree may be short, but it may not be selective.

    Its whole risk is that it is a hand-picked subset that quietly stops
    matching the repository.  It is not hand-picked -- it is every depth-0
    entry of `TREE`, which `test_tree_matches_git` already ties to
    ``git ls-files`` -- and this says so, so that a future edit cannot turn it
    into a curated list without failing.
    """
    rendered = '\n'.join(render_summary_tree())
    top = [p for p, _ in TREE if p.rstrip('/').count('/') == 0]
    assert top, 'TREE has no top-level entries, which cannot be right'
    for path in top:
        name = path.rstrip('/').split('/')[-1] + ('/' if path.endswith('/') else '')
        assert name in rendered, (
            '%s is a top-level entry but is missing from the README summary' % name)
    # ...and nothing deeper leaked in: one line per entry, plus the root label.
    assert len(render_summary_tree()) == len(top) + 1


def test_every_top_level_directory_is_described():
    r"""A bare directory name in the README summary tells a reader nothing.

    The full tree can leave a directory uncommented because its children are
    enumerated underneath it.  The summary has no children to fall back on, so
    every top-level entry has to carry its own one-line comment.
    """
    missing = [p for p, c in TREE
               if p.rstrip('/').count('/') == 0 and not c]
    assert not missing, 'top-level entries without a comment: %s' % missing


def test_installation_rst_tree_is_generated():
    r"""installation.rst carries the same tree, indented for rst."""
    assert current_install_tree() == render_tree(), (
        'the file tree in docs/source/installation.rst is out of date; '
        'regenerate it with `python tests/test_file_tree.py --write`')


if __name__ == '__main__':
    if '--write' in sys.argv:
        for path in write() or []:
            print('rewrote %s' % os.path.relpath(path, ROOT))
        else:
            pass
    else:
        ok = (current_readme_tree() == render_tree()
              and current_install_tree() == render_tree())
        print('file tree is %s' % ('up to date' if ok else 'OUT OF DATE'))
        sys.exit(0 if ok else 1)
