# -*- coding: utf-8 -*-
r"""gen_mp_reference.py

An extended-precision reference for the profile behind Figure 11, to replace the
double-precision DOP853 one that currently sets the floor.

WHY.  The DOP853 referee in ``gen_profile_benchmarks.py`` runs at rtol 1e-12 in double
precision.  Measured against itself at rtol 1e-13 it is uncertain by 1.1e-13 (3nu),
2.3e-11 (4nu) and 5.2e-11 (5nu) -- which is 1.1x the floor every series in the figure
settles onto.  Nothing at the bottom of those curves is a property of the codes being
compared; it is the ruler.  This script builds a ruler four to five decades finer.

HOW.  The same construction Figure 2 uses: a midpoint slab product carried in ``mpmath``
and Richardson-extrapolated three times, removing the N^-2, N^-4 and N^-6 terms of the
midpoint rule in turn.  The Hamiltonian is taken at double precision and promoted, so the
reference answers "what is the exact evolution generated by *this* Hamiltonian" -- the
discretization error is what gets removed, and that is what limits DOP853 here.

THE INDEPENDENCE CAVEAT, STATED RATHER THAN HIDDEN.  A midpoint slab product is
NuOscProbExact's own algorithm, and Section 4.6 of the paper shows it is also the Magnus
method at second order.  So this referee shares its construction with both codes it
judges, where the DOP853 one deliberately shared with neither.  That is why every case
also records ``ode_crosscheck``: the agreement between this ladder and the existing
DOP853 answer.  If the two agree far below the old floor, the shared structure
demonstrably hid nothing, and the ladder can be trusted below where DOP853 cannot follow.

    python notebooks/gen_mp_reference.py

Writes ``mp_reference_profile.json``, checkpointing after every (flavour, energy) so a
long run is never lost.  Progress goes to stderr.
"""

__author__ = "Mauricio Bustamante"
__email__ = "mbustamante@gmail.com"

import json
import pathlib
import platform
import sys
import time

import numpy as np
from mpmath import mp

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import gen_profile_benchmarks as gpb                      # noqa: E402

HERE = pathlib.Path(__file__).parent
OUT = HERE/'mp_reference_profile.json'

DPS = 30                 # H enters at double precision, so below ~1e-16 is meaningless
TARGET = 1.0e-15         # four decades under the 3nu floor, five under the 4nu one
BASE0 = 32
BASE_CAP = 4096
# Below this the coarse ladders alias a feature of the profile at four and five flavours:
# measured at E4/4nu, bases 32-256 converge smoothly onto 0.1926988 with a self-consistency
# of 5.9e-16, and only at n = 512 does the sequence jump to the true 0.1926925.  A ladder
# sitting entirely inside that first plateau certifies a number it has no right to, so the
# floor is a correctness guard rather than a performance setting.
BASE_MIN_MANY_FLAVOUR = 512
# Loose sanity gate against the independent DOP853 answer.  Far above its own noise
# (2e-11 at 4nu) so it never rejects a good point, far below the 6e-6 that false
# convergence produced, so it always rejects that.
ODE_GATE = 1.0e-8


def mp_midpoint(hf, L, n, d):
    """Midpoint slab product of exp(-i H h), carried in mpmath."""
    h = mp.mpf(L)/n
    xs = [(k + 0.5)*float(L)/n for k in range(n)]
    Hs = hf(np.asarray(xs))                        # (n, d, d), double precision
    U = mp.eye(d)
    for k in range(n):
        M = mp.matrix([[mp.mpc(complex(Hs[k][i, j])) for j in range(d)]
                       for i in range(d)])
        U = mp.expm(-1j*M*h)*U
    return U


def richardson3(P, ns):
    """Remove N^-2, N^-4 and N^-6 in turn, staying in mpmath throughout."""
    Q = {n: (4*P[2*n] - P[n])/3 for n in ns[:-1]}
    R = {n: (16*Q[2*n] - Q[n])/15 for n in ns[:-2]}
    T = (64*R[ns[1]] - R[ns[0]])/63
    return T, float(max(abs(x) for x in (T - R[ns[1]])))


def reference_at(hf, L, d, nu_i, nu_f, ode):
    """Triple-Richardson probability, with the base count raised until it converges.

    The ladders overlap: doubling the base from b to 2b reuses three of its four slab
    counts, so ``P`` is memoized across attempts.  Without that, each doubling repeats
    work already done and the high-phase cases cost about twice what they need to.
    """
    P = {}
    base = BASE0 if d < 4 else BASE_MIN_MANY_FLAVOUR
    while True:
        ns = (base, 2*base, 4*base, 8*base)
        for n in ns:
            if n not in P:
                U = mp_midpoint(hf, L, n, d)
                P[n] = mp.matrix([[abs(U[i, j])**2 for j in range(d)]
                                  for i in range(d)])
        T, sc = richardson3(P, ns)
        val = float(T[nu_f, nu_i])
        # Self-convergence alone is not an acceptance criterion -- it is exactly what
        # the false plateau satisfied.  The independent DOP853 answer has to agree too.
        if (sc < TARGET and abs(val - ode) < ODE_GATE) or base >= BASE_CAP:
            return val, sc, base
        base *= 2


def main():
    prof = gpb.exponential_profile()
    E, L = prof['energies'], prof['baseline']
    mp.dps = DPS
    out = {'what': 'triple-Richardson mpmath midpoint-product reference for Fig. 11',
           'dps': DPS, 'target_self_convergence': TARGET,
           'machine': platform.platform(), 'cases': []}
    if OUT.exists():                                # resume a partial run
        out = json.loads(OUT.read_text())
    done = {(c['flavours'], i) for c in out['cases'] for i in range(len(c['reference']))}

    for d in (2, 3, 4, 5):
        case = next((c for c in out['cases'] if c['flavours'] == d), None)
        if case is None:
            case = {'flavours': d, 'reference': [], 'self_convergence': [],
                    'base_slabs': [], 'ode_crosscheck': []}
            out['cases'].append(case)
        print('--- %d flavours ---' % d, file=sys.stderr, flush=True)
        hf = gpb.h_of(d, prof['vcc'], None)         # placeholder; rebuilt per energy
        for j, e in enumerate(E):
            if j < len(case['reference']):
                continue
            t0 = time.time()
            hf = gpb.h_of(d, prof['vcc'], e)
            ode = gpb.referee(d, prof['vcc'], e, L)
            val, sc, base = reference_at(hf, L, d, gpb.gd.NUMU, gpb.gd.NUMU, ode)
            case['reference'].append(val)
            case['self_convergence'].append(sc)
            case['base_slabs'].append(base)
            case['ode_crosscheck'].append(abs(val - ode))
            OUT.write_text(json.dumps(out, indent=1))
            print('  E %2d/%d  P=%.15f  self-conv %.1e  base %4d  vs DOP853 %.1e  (%.0fs)'
                  % (j + 1, len(E), val, sc, base, abs(val - ode), time.time() - t0),
                  file=sys.stderr, flush=True)
    print('wrote %s' % OUT.name, file=sys.stderr)


if __name__ == '__main__':
    main()
